// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Collection struct {
	Filename       string
	CollectionName string
	Content        string
	Metadata       string
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}
